apiVersion: v2
name: katago-server
description: A Helm chart for KataGo Server - High-performance REST API server for KataGo
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.2.1

# This is the version number of the application being deployed.
appVersion: "1.1.0"

keywords:
  - katago
  - go
  - game
  - ai
  - rest-api

home: https://github.com/stubbi/katago-server
sources:
  - https://github.com/stubbi/katago-server

maintainers:
  - name: stubbi
    url: https://github.com/stubbi

icon: https://raw.githubusercontent.com/lightvector/KataGo/master/images/icon.png
